language: python

python:
  - "2.7"

install:
  - pip install ansible

script:
  - ansible-playbook -i ansible/tests/ansible.inventory ansible/playbook.yml

notifications:
  email:
    - jandrob1978+travisci@gmail.com