---
language: python

python: "2.7"

before_install:
  - sudo apt-get update 
  - sudo apt-get install python-software-properties
  - sudo FORCE_ADD_APT_REPOSITORY=1 add-apt-repository ppa:rquillo/ansible
  - sudo apt-get update

install:
  - sudo apt-get install ansible

script:
  - sudo ansible --version
  - sudo ansible-playbook -i ansible/tests/ansible.inventory --connection=local --sudo -vvvv ansible/playbook.yml

notifications:
  email:
    - jandrob1978+travisci@gmail.com