---
language: python

python: "2.7"

before_install:
 - sudo apt-get update 
 - sudo apt-get install python-apt
 - sudo apt-get install python-pycurl
 - sudo apt-get install python-software-properties

install:
  - pip install ansible

script:
  - ansible-playbook -i ansible/tests/ansible.inventory --connection=local --sudo -vvvv ansible/playbook.yml

notifications:
  email:
    - jandrob1978+travisci@gmail.com